[package]
name = "clerr"
version = "0.8.0-rc.2"
description = "This library aids in command-line error reporting."
readme = "README.md"
repository = "https://github.com/nikdeapen/clerr"
homepage = "https://github.com/nikdeapen/clerr"
authors = ["Nik Deapen <nik@deapen.com>"]
edition = "2021"
license = "MIT"

[dependencies]
colored = "3.0.0"
